#%%

# Creating Leung & Nomoto (2018) yield tables for SNIa.

#%%

import numpy as np
import h5py
from datetime import datetime

def make_SNIa_tables():

    species_names = ['Hydrogen', 'Helium', 'Carbon', 'Nitrogen', 'Oxygen',
                     'Neon', 'Magnesium', 'Silicon', 'Iron']

    num_species = 9

    # Taken from Leung & Nomoto (2018) table 12. They recomputed their original Ch-model with
    # updated nuclear reaction network. These yields are for their solar metallicity model and include all isotopes.
    yields = np.array([0, 0,
                       5.2e-2,  # C
                       9.56e-10 + 1.35e-10,  # N
                       1.85e-1,  # O
                       2.73e-3 + 1.62e-3 + 6.97e-8,  # Ne
                       4.26e-3 + 1.81e-5 + 2.35e-5,  # Mg
                       1.55e-1 + 7.73e-4 + 1.64e-3,  # Si
                       1.15e-1 + 6.68e-1 + 1.96e-2 + 5.46e-4  # Fe
                       ])

    metal_mass_lost = 1.30  # Msun

    # Write data to HDF5
    with h5py.File('./data/SNIa.hdf5', 'w') as data_file:
        Header = data_file.create_group('Header')

        description = "Yields for SNIa stars (in units of solar mass) taken from Leung & Nomoto et al. (2018)"
        Header.attrs["Description"] = np.string_(description)

        contact = "Dataset generated by Camila Correa (University of Amsterdam). Email: camila@camilacorrea.com,"
        contact += " website: camilacorrea.com"
        Header.attrs["Contact"] = np.string_(contact)

        # date_int = int(datetime.today().strftime('%Y%m%d'))
        # date_string = data_file.create_dataset('Date_string', data=np.array([date_int]))
        date_string = data_file.create_dataset('Date_string', data=np.array([20230331])) # Frozen

        Reference = np.string_(['Leung, S. & Nomoto, K., (2018) ApJ, 861, 2, 143'])
        data_file.create_dataset('Reference', data=Reference)

        data_file.create_dataset('Number_of_species', data=np.array([num_species]))

        Element_names = np.string_(species_names)
        dt = h5py.string_dtype(encoding='ascii')
        data_file.create_dataset('Species_names', dtype=dt, data=Element_names)

        data_file.create_dataset('Total_Metals', data=metal_mass_lost)

        data_file.create_dataset('Yield', data=yields)


